apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: ns-sample
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: nginx:latest 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-hello
  namespace: ns-sample
spec:
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 80
