name: Terraform Pipeline

on:
  push:
    paths:
      - 'tf/**'
  
  pull_request:
    paths:
      - 'tf/**'

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Fmt Check
        run: terraform fmt -check tf

      - name: Terraform Validate
        run: terraform validate tf

      - name: TFSec Scan
        uses: aquasecurity/tfsec-action@v1
        with:
          tfsec_version: latest
          args: --no-color tf

      - name: Terraform Plan
        run: terraform plan -no-color -input=false tf

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan 
    
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    environment:
      name: production
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init tf

      - name: Terraform Plan
        run: terraform plan -no-color -input=false tf

      - name: Terraform Apply
        run: terraform apply -auto-approve tf

