name: Terraform Pipeline

on:
  push:
    paths:
      - 'tf/mgmt/**'
  
  pull_request:
    paths:
      - 'tf/mgmt/**'

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: tf/mgmt
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::443370681532:role/github-oidc-role
          aws-region: ap-northeast-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Fmt
        run: terraform fmt -recursive

      - name: Commit and Push Format Changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Auto-format: fix Terraform style [ci skip]"
            git push
          else
            echo "No formatting changes to commit."
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: TFSec Scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          tfsec_version: latest

      - name: Terraform Plan
        run: terraform plan -input=false

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan 
    defaults:
      run:
        working-directory: tf/mgmt
    
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    environment:
      name: production
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve

